spring:
   datasource:
      username: pet_store
      password: pet_store@123
      url: jdbc:mysql://localhost:3306/pet_store
      
   jpa:
      hibernate:
         ddl-auto: create
      show-sql: true 
      defer_datasource_initialization: true
      
   sql:
      init:
         mode: always